# Full Python + pip environment (no ensurepip needed)
[phases.setup]
nixPkgs = ["python311Full"]

# Cache pip packages for faster redeploys
[phases.install]
cacheDirectories = ["/root/.cache/pip"]
cmds = [
  "pip install --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
