# Explicitly tell Nixpacks to use Python
[build]
language = "python"

[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cacheDirectories = ["/root/.cache/pip"]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
