[build]
language = "python"

[phases.setup]
# Provide Python + pip
nixPkgs = ["python311Full", "python311Packages.pip", "gcc"]

[phases.install]
cacheDirectories = ["/root/.cache/pip"]
cmds = [
  # Create a writable virtual environment
  "python -m venv /app/venv",
  # Activate it
  ". /app/venv/bin/activate",
  # Upgrade pip inside venv
  "pip install --upgrade pip",
  # Install your dependencies
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = []

[start]
# Run FastAPI using the virtualenv python
cmd = "/app/venv/bin/uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
