# Force Python + pip installation at the system level
[build]
language = "python"

[phases.setup]
# Explicitly include pip as a nix package (this guarantees it's available)
nixPkgs = ["python311Full", "python311Packages.pip", "gcc"]

[phases.install]
cacheDirectories = ["/root/.cache/pip"]
cmds = [
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
