[build]
language = "python"

[phases.setup]
nixPkgs = ["python311Full", "python311Packages.pip", "gcc", "redis"]

[phases.install]
cmds = [
  "pip install --no-cache-dir -r requirements.txt",
  "pip install --no-cache-dir redis hiredis"  # Fast Redis client
]

[phases.build]
cmds = []

[start]
cmd = "gunicorn main:app -w 2 -k uvicorn.workers.UvicornWorker --timeout 120"
