[build]
language = "python"

[phases.setup]
# Install Python + pip
nixPkgs = ["python311Full", "python311Packages.pip", "gcc"]

[phases.install]
cacheDirectories = ["/root/.cache/pip"]
cmds = [
  """
  python -m venv /app/venv && \
  /app/venv/bin/pip install --upgrade pip && \
  /app/venv/bin/pip install --no-cache-dir -r requirements.txt
  """
]

[phases.build]
cmds = []

[start]
# Run FastAPI using the venv
cmd = "/app/venv/bin/uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
